version: '3.9'

services:
  fraud-detection-api:
    container_name: fraud-detection-api
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
